### ISSUE TITLE
Short tag problem

### ISSUE THREAD

**Issue by 1000k** [chriskite/phactory#1]
Hi chriskite.

I like this idea so much for relieving pain with DB testing.

By the way, I hit problem when requiring Phactory classes with PHPUnit.
I surely specified correct path to 'Phactory.php', but following error was appeard: 

{{{
Fatal error: Class 'Phactory' not found in C:\work\scripts\excercise\src\tests\class\models\excerciseTest.php on line 26
}}}

Finally, I found that the problem is solved by rewriting all "<?" to "<?php".
It seems php short tags cause this problem.

It will need to be fixed.

**Comment by denheck** [comment]
Thank you for your help. The problem has been fixed and will be released in the next version of Phactory.
