### ISSUE TITLE
Inflector.php conflicts with existing Inflector.php in CakePHP

### ISSUE THREAD

**Issue by SuperWes** [chriskite/phactory#10]
I'm evaluating Phactory to create PHPUnit tests on a project that uses a pre-Cake 2.0 version CakePHP. When I first pulled it down I was getting errors that the Inflector class conflicts with the Inflector class in CakePHP. This made it impossible to use the pear'd version.

I've renamed the class locally to Inflector_p for evaluation purposes, but it might be worth adding a namespace or changing the name to something less common to avoid issues like this.

**Comment by ramsey** [comment]
Pull request #17, if accepted, would resolve this issue.

**Comment by jimbojsb** [comment]
Closed, per @ramsey above
